name: Test Google Cloud Authentication

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify authentication
        run: gcloud auth list