name: Build Test Push and Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Start container
        run: |
          docker run -d \
            -p 8080:80 \
            --name html-container \
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

      - name: Test website
        run: |
          curl --fail --retry 5 --retry-delay 2 http://localhost:8080/

      - name: Stop container
        if: always()
        run: |
          docker rm -f html-container || true

      - name: Push image to Artifact Registry
        run: |
          docker push \
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.IMAGE_NAME }} \
            --image=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }} \
            --project=${{ vars.PROJECT_ID }} \
            --region=${{ vars.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --quiet

      - name: Display Cloud Run URL
        run: |
          gcloud run services describe ${{ vars.IMAGE_NAME }} \
            --project=${{ vars.PROJECT_ID }} \
            --region=${{ vars.REGION }} \
            --format="value(status.url)"